components:
  requestBodies: {}
  securitySchemes:
    x-redlock-auth:
      description: The x-redlock-auth value is a JSON Web Token (JWT).
      in: header
      name: x-redlock-auth
      type: apiKey
  schemas:
    AnomaliesSettingsRequestModel:
      description: Model for Anomaly Settings Request
      properties:
        alertDisposition:
          description: Alert Disposition Setting
          enum:
          - Aggressive
          - Moderate
          - Conservative
          type: string
        alertDispositionDescription:
          additionalProperties:
            type: string
          description: Alert disposition description
          type: object
        policyDescription:
          description: Policy description
          type: string
        policyName:
          description: Policy name
          type: string
        trainingModelDescription:
          additionalProperties:
            type: string
          description: Training model description
          type: object
        trainingModelThreshold:
          description: Training Model Threshold
          enum:
          - Low
          - Medium
          - High
          type: string
      type: object
info:
  contact: {}
  description: "Set the enterprise level settings to build standard training models\
    \ for anomaly detection, alert disposition, \nand some other global settings such\
    \ as the timeout before the user is looked out for inactivity and user \nattribution\
    \ for alerts.\n"
  title: Prisma Cloud Anomaly Settings API Overview
  version: Latest
openapi: 3.0.0
paths:
  /anomalies/settings:
    get:
      description: Returns all anomaly settings. The response object is a list of
        policy IDs, and anomaly settings are returned with each policy ID.
      operationId: get-all-anomalies-settings
      parameters:
      - description: Type
        in: query
        name: type
        required: true
        schema:
          enum:
          - Network
          - UEBA
          type: string
      responses:
        '200':
          content:
            '*/*':
              schema:
                additionalProperties:
                  $ref: '#/components/schemas/AnomaliesSettingsRequestModel'
                type: object
          description: successful operation
        '400':
          description: missing_required_parameter / invalid_parameter_value / internal_error
        '403':
          description: permission_error
      security:
      - x-redlock-auth: []
      summary: Get All Anomaly Settings
      tags:
      - Anomaly Settings
  /anomalies/settings/{policyid}:
    get:
      description: Returns anomaly settings for the specified policy ID.
      operationId: get-anomalies-settings
      parameters:
      - description: Policy ID
        in: path
        name: policyid
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AnomaliesSettingsRequestModel'
          description: successful operation
        '400':
          description: missing_required_parameter / invalid_parameter_value / internal_error
        '403':
          description: permission_error
      security:
      - x-redlock-auth: []
      summary: Get Anomaly Settings
      tags:
      - Anomaly Settings
    post:
      description: Updates anomaly settings for the policy with the specified ID.
      operationId: update-anomalies-settings
      parameters:
      - description: Policy ID
        in: path
        name: policyid
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnomaliesSettingsRequestModel'
        description: Model for Anomaly Settings Request
      responses:
        '200':
          description: successful operation
        '400':
          description: missing_required_parameter / invalid_parameter_value / internal_error
        '403':
          description: permission_error
      security:
      - x-redlock-auth: []
      summary: Update Anomaly Settings
      tags:
      - Anomaly Settings
servers:
- url: https://api.prismacloud.io
tags:
- description: The endpoints to manage anomaly setting thresholds and alert disposition
    for anomalies are listed below.
  name: Anomaly Settings