components:
  requestBodies:
    AnomaliesTrustedListSummaryModel:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AnomaliesTrustedListSummaryModel'
      description: Model for Anomaly Trusted List Request
  securitySchemes:
    x-redlock-auth:
      description: The x-redlock-auth value is a JSON Web Token (JWT).
      in: header
      name: x-redlock-auth
      type: apiKey
  schemas:
    AnomaliesTrustedListEntryModel:
      description: Model for Anomaly Trusted List Entry
      properties:
        imageID:
          description: Image ID
          type: string
        ipCIDR:
          description: IP CIDR Block
          type: string
        port:
          description: Port
          type: string
        resourceID:
          description: Resource ID
          type: string
        service:
          description: Service
          type: string
        subject:
          description: Subject name
          type: string
        tagKey:
          description: Tag key
          type: string
        tagValue:
          description: Tag value
          type: string
      type: object
    AnomaliesTrustedListSummaryBeanModel:
      description: Model for AnomaliesTrustedListSummaryBean
      properties:
        accountID:
          description: Account ID
          type: string
        accountName:
          description: Account name
          readOnly: true
          type: string
        applicablePolicies:
          description: List of applicable policies
          items:
            type: string
          type: array
        createdBy:
          description: Created by
          readOnly: true
          type: string
        createdOn:
          description: creation timestamp
          format: int64
          readOnly: true
          type: integer
        createdRoleId:
          description: Role ID of user who created trusted list
          readOnly: true
          type: string
        createdRoleTypeId:
          description: Role type ID of user who created trusted list
          format: int32
          readOnly: true
          type: integer
        customerID:
          description: Customer ID
          format: int32
          readOnly: true
          type: integer
        description:
          description: Anomaly description
          type: string
        id:
          description: Anomalies trusted list ID
          format: int32
          readOnly: true
          type: integer
        modifiedBy:
          description: Modified by
          readOnly: true
          type: string
        modifiedOn:
          description: Modification timestamp
          format: int64
          readOnly: true
          type: integer
        modifiedRoleId:
          description: Role ID of user who last modified trusted list
          readOnly: true
          type: string
        modifiedRoleTypeId:
          description: Role type ID of user who last modified trusted list
          format: int32
          readOnly: true
          type: integer
        name:
          description: Anomaly name
          type: string
        trustedListEntries:
          description: List of network anomalies in the trusted list
          items:
            $ref: '#/components/schemas/NetworkAnomaliesTrustedListEntryModel'
          type: array
        trustedListType:
          description: Trusted list type
          type: string
        vpc:
          description: Virtual private cloud
          type: string
      type: object
    AnomaliesTrustedListSummaryModel:
      description: Model for Anomaly Trusted List Request
      properties:
        accountID:
          description: Account ID. Default is "any".
          type: string
        applicablePolicies:
          description: Applicable Policies
          items:
            type: string
          type: array
        description:
          description: Reason for trusted listing
          type: string
        name:
          description: Name of the trusted list
          type: string
        trustedListEntries:
          description: Trusted list entries
          items:
            $ref: '#/components/schemas/AnomaliesTrustedListEntryModel'
          type: array
        trustedListType:
          description: Trusted list type
          enum:
          - ip
          - resource
          - image
          - tag
          - service
          type: string
        vpc:
          description: VPC. Default is "any".
          type: string
      required:
      - applicablePolicies
      - name
      - trustedListType
      type: object
    AnomaliesTrustedListTypeEntryModel:
      description: Model for Anomaly Trusted List Type Entry
      properties:
        applicableCategories:
          description: List of trusted list type applicable categories
          items:
            type: string
          type: array
        description:
          description: Trusted list type description
          type: string
        name:
          description: Trusted list type name
          type: string
      type: object
    NetworkAnomaliesTrustedListEntryModel:
      description: Model for NetworkAnomaliesTrustedListEntry
      properties:
        imageID:
          description: Image ID
          readOnly: true
          type: string
        ipCIDR:
          description: IP CIDR block
          readOnly: true
          type: string
        port:
          description: Port
          readOnly: true
          type: string
        resourceID:
          description: Resource ID
          readOnly: true
          type: string
        service:
          description: Service
          readOnly: true
          type: string
        subject:
          description: Subject Name
          readOnly: true
          type: string
        tagKey:
          description: Tag key
          readOnly: true
          type: string
        tagValue:
          description: Tag value
          readOnly: true
          type: string
      type: object
info:
  contact: {}
  description: "Exclude trusted IP addresses when conducting tests for PCI compliance\
    \ or penetration testing on your network. \nAny addresses included in this list\
    \ do not generate alerts against the Prisma Cloud Anomaly Policies that \ndetect\
    \ unusual network activity such as the policies that detect internal port scan\
    \ and port sweep activity, \nwhich are enabled by default.\n"
  title: Prisma Cloud Anomaly Trusted List API Overview
  version: Latest
openapi: 3.0.0
paths:
  /anomalies/trusted_list:
    get:
      description: Returns all entries in the Anomaly Trusted List.
      operationId: list-trusted-listed-anomalies
      responses:
        '200':
          content:
            '*/*':
              schema:
                items:
                  $ref: '#/components/schemas/AnomaliesTrustedListSummaryBeanModel'
                type: array
          description: successful operation
        '400':
          description: missing_required_parameter / invalid_parameter_value / internal_error
        '403':
          description: permission_error
      security:
      - x-redlock-auth: []
      summary: Get Anomaly Trusted List
      tags:
      - Anomaly Trusted List
  /anomalies/trusted_list/{id}:
    post:
      description: Modifies an existing entry in the Anomaly Trusted List.
      operationId: update-trusted-list-anomalies
      parameters:
      - in: path
        name: id
        required: true
        schema:
          format: int32
          type: integer
      requestBody:
        $ref: '#/components/requestBodies/AnomaliesTrustedListSummaryModel'
      responses:
        '200':
          content:
            '*/*':
              schema:
                items:
                  format: int32
                  type: integer
                type: array
          description: successful operation
        '400':
          description: missing_required_parameter / invalid_parameter_value / internal_error
        '403':
          description: permission_error
      security:
      - x-redlock-auth: []
      summary: Update Anomaly Trusted List Entry
      tags:
      - Anomaly Trusted List
    delete:
      description: Deletes the entry with the given ID from the Anomaly Trusted List.
      operationId: delete-trusted-list-anomalies
      parameters:
      - in: path
        name: id
        required: true
        schema:
          format: int32
          type: integer
      responses:
        '200':
          description: successful operation
        '400':
          description: missing_required_parameter / invalid_parameter_value / internal_error
        '403':
          description: permission_error
      security:
      - x-redlock-auth: []
      summary: Delete Anomaly Trusted List Entry
      tags:
      - Anomaly Trusted List
    get:
      description: Returns the entry with the specified ID from the Anomaly Trusted
        List.
      operationId: list-trusted-listed-anomaly
      parameters:
      - in: path
        name: id
        required: true
        schema:
          format: int32
          type: integer
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AnomaliesTrustedListSummaryBeanModel'
          description: successful operation
        '400':
          description: missing_required_parameter / invalid_parameter_value / internal_error
        '403':
          description: permission_error
      security:
      - x-redlock-auth: []
      summary: Get Anomaly Trusted List Entry
      tags:
      - Anomaly Trusted List
  /anomalies/policies:
    get:
      description: Returns a list of available policies for a specific trusted list
        type.
      operationId: list-available-policies
      parameters:
      - description: Trusted list type
        in: query
        name: trustedListType
        required: true
        schema:
          enum:
          - ip
          - resource
          - image
          - tag
          - service
          - port
          type: string
      responses:
        '200':
          content:
            '*/*':
              schema:
                additionalProperties:
                  type: string
                type: object
          description: successful operation
        '400':
          description: missing_required_parameter/invalid_parameter_value/internal_error
        '403':
          description: permission_error
      security:
      - x-redlock-auth: []
      summary: List Policies for Trusted List Type
      tags:
      - Anomaly Trusted List
  /anomalies/trusted_list/types:
    get:
      description: Returns the  available trusted list types.
      operationId: list-allowed-trustedlist-types
      responses:
        '200':
          content:
            '*/*':
              schema:
                additionalProperties:
                  $ref: '#/components/schemas/AnomaliesTrustedListTypeEntryModel'
                type: object
          description: successful operation
        '400':
          description: missing_required_parameter/invalid_parameter_value/internal_error
        '403':
          description: permission_error
      security:
      - x-redlock-auth: []
      summary: List Allowed Trusted List Types
      tags:
      - Anomaly Trusted List
servers:
- url: https://api.prismacloud.io
tags:
- description: THe endpoints to manage anomaly trusted lists are listed below.
  name: Anomaly Trusted List
