---
openapi: 3.0.3
info:
  title: Command Center Vulnerability Swim Lane APIs
  version: Latest
tags:
  - name: Command Center
    description: Command Center Vulnerability Swim Lane APIs
paths:
  /commandcenter/v1/top-vulnerabilities:
    post:
      tags:
        - Command Center Vulnerability Swim Lane APIs
      summary: List Top Vulnerabilities
      description: Gets the data for the vulnerable images and hosts based on the type for the requested time, accounts and account groups
      operationId: command-center-list-top-vulnerabilities
      parameters:
        - name: limit
          in: query
          schema:
            format: int64
            type: integer
        - name: type
          in: query
          schema:
            type: string
        - name: x-redlock-auth
          in: header
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VulnerabilityRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VulnerabilityResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "429":
          description: Too Many Requests
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "503":
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        target:
          type: string
    ErrorResponse:
      type: object
      properties:
        error:
          $ref: '#/components/schemas/Error'
    Filter:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/FilterType'
        operator:
          type: string
        value:
          type: string
    FilterType:
      enum:
        - account.group
        - cloud.account
      type: string
    TimeRangeConfig:
      type: object
      properties:
        type:
          type: string
        value:
          type: object
    VulnerableAssets:
      type: object
      properties:
        unifiedAssetId:
          type: string
        resourceName:
          type: string
        numCriticalVulnerabilities:
          format: int64
          type: integer
        numHighVulnerabilities:
          format: int64
          type: integer
        totalVulnerabilities:
          format: int64
          type: integer
    VulnerabilityRequest:
      type: object
      properties:
        filters:
          type: array
          items:
            $ref: '#/components/schemas/Filter'
        timeRange:
          $ref: '#/components/schemas/TimeRangeConfig'
    VulnerabilityResponse:
      type: object
      properties:
        value:
          type: array
          items:
            $ref: '#/components/schemas/VulnerableAssets'
        date:
          type: string
  securitySchemes:
    x-redlock-auth:
      description: The x-redlock-auth value is a JSON Web Token (JWT).
      in: header
      name: x-redlock-auth
      type: apiKey
